# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.auth_keys.post import CreateApiKeyRaw
from browser_cat_python_sdk.paths.auth_keys_key_id.get import GetKeyRaw
from browser_cat_python_sdk.paths.auth_keys.get import ListAllRaw
from browser_cat_python_sdk.paths.auth_keys_key_id.delete import RevokeKeyRaw
from browser_cat_python_sdk.paths.auth_keys_key_id.put import UpdateApiKeyRaw
from browser_cat_python_sdk.paths.auth_keys_key_id.patch import UpdateKeyRaw


class APIKeysApiRaw(
    CreateApiKeyRaw,
    GetKeyRaw,
    ListAllRaw,
    RevokeKeyRaw,
    UpdateApiKeyRaw,
    UpdateKeyRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
