# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.auth_keys.post import CreateApiKey
from browser_cat_python_sdk.paths.auth_keys_key_id.get import GetKey
from browser_cat_python_sdk.paths.auth_keys.get import ListAll
from browser_cat_python_sdk.paths.auth_keys_key_id.delete import RevokeKey
from browser_cat_python_sdk.paths.auth_keys_key_id.put import UpdateApiKey
from browser_cat_python_sdk.paths.auth_keys_key_id.patch import UpdateKey
from browser_cat_python_sdk.apis.tags.api_keys_api_raw import APIKeysApiRaw


class APIKeysApi(
    CreateApiKey,
    GetKey,
    ListAll,
    RevokeKey,
    UpdateApiKey,
    UpdateKey,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: APIKeysApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = APIKeysApiRaw(api_client)
