# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.billing_subscriptions_current.get import GetActiveSubscription
from browser_cat_python_sdk.paths.billing_invoices_inv_id_pdf.get import GetInvoicePdf
from browser_cat_python_sdk.paths.billing_invoices_inv_id.get import GetSpecificInvoice
from browser_cat_python_sdk.paths.billing_subscriptions_sub_id.get import GetSpecificSubscription
from browser_cat_python_sdk.paths.billing_invoices.get import ListInvoicesRange
from browser_cat_python_sdk.paths.billing_subscriptions.get import ListSubscriptionsWithinRange
from browser_cat_python_sdk.apis.tags.billing_api_raw import BillingApiRaw


class BillingApi(
    GetActiveSubscription,
    GetInvoicePdf,
    GetSpecificInvoice,
    GetSpecificSubscription,
    ListInvoicesRange,
    ListSubscriptionsWithinRange,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BillingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BillingApiRaw(api_client)
