# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.connect.get import EstablishConnection
from browser_cat_python_sdk.apis.tags.browsers_api_raw import BrowsersApiRaw


class BrowsersApi(
    EstablishConnection,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BrowsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BrowsersApiRaw(api_client)
