# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.openapi.get import ExploreFunctionality
from browser_cat_python_sdk.paths.openapi_json.get import GetSpecJson
from browser_cat_python_sdk.paths.openapi_yaml.get import GetYamlSpec
from browser_cat_python_sdk.apis.tags.open_api_api_raw import OpenAPIApiRaw


class OpenAPIApi(
    ExploreFunctionality,
    GetSpecJson,
    GetYamlSpec,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OpenAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OpenAPIApiRaw(api_client)
