# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.openapi.get import ExploreFunctionalityRaw
from browser_cat_python_sdk.paths.openapi_json.get import GetSpecJsonRaw
from browser_cat_python_sdk.paths.openapi_yaml.get import GetYamlSpecRaw


class OpenAPIApiRaw(
    ExploreFunctionalityRaw,
    GetSpecJsonRaw,
    GetYamlSpecRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
