# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.health.get import CheckHealthStatus
from browser_cat_python_sdk.paths.metrics.get import ShowMetrics
from browser_cat_python_sdk.apis.tags.server_api_raw import ServerApiRaw


class ServerApi(
    CheckHealthStatus,
    ShowMetrics,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ServerApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ServerApiRaw(api_client)
