# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.health.get import CheckHealthStatusRaw
from browser_cat_python_sdk.paths.metrics.get import ShowMetricsRaw


class ServerApiRaw(
    CheckHealthStatusRaw,
    ShowMetricsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
