# coding: utf-8

"""
    BrowserCat API

    Providing purr-fect headless browser access via utility endpoints and direct websocket connections.

    The version of the OpenAPI document: 1.0.0
    Contact: support@browsercat.com
    Created by: https://www.browsercat.com/contact
"""

from browser_cat_python_sdk.paths.usage_sessions_session_id_events_event_id.get import GetEventData
from browser_cat_python_sdk.paths.usage_sessions_session_id.get import GetRequestData
from browser_cat_python_sdk.paths.usage_sessions.get import GetSessionRange
from browser_cat_python_sdk.paths.usage_buckets.get import ListAggregateAccountUsage
from browser_cat_python_sdk.paths.usage_sessions_session_id_events.get import ListRequestEvents
from browser_cat_python_sdk.apis.tags.usage_api_raw import UsageApiRaw


class UsageApi(
    GetEventData,
    GetRequestData,
    GetSessionRange,
    ListAggregateAccountUsage,
    ListRequestEvents,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsageApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsageApiRaw(api_client)
